get http://localhost:3000/api/userBalance/1

####
post http://localhost:3000/api/transaction/1
Content-Type: application/json

{
    "amount": 360,
    "description": "Local",
    "idCategory": 5,
    "idAccount": 1,
    "isIncome": 4
}

####
put http://localhost:3000/api/transaction/1

####
PATCH   http://localhost:3000/api/transaction/1

####
get http://localhost:3000/api/bd